### creating metrix

In [1]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


#### creating vectors

In [2]:
import numpy


In [3]:
x=numpy.array([1,4,6,8])
y=numpy.array([2,4,5,1])
z=x+y
print(z)

[ 3  8 11  9]


In [4]:
type(z)

numpy.ndarray

In [5]:
z.shape ### one dimesion if it is 2 dimentiom something will after 4,

(4,)

In [7]:
z.size

4

In [8]:
z.ndim ### no.of dimention of an array

1

In [9]:
z.dtype

dtype('int32')

In [10]:
z.itemsize

4

In [11]:
z.data ### memory location will print

In [12]:
z

array([ 3,  8, 11,  9])

### numpy statistics

In [15]:
a=np.array([1,4,3,8,9,2,3],float)
np.median(a)

3.0

In [16]:
a=np.array([[1,2,1,3],[5,3,1,8]],float)
c=np.corrcoef(a)
c

array([[1.        , 0.72870505],
       [0.72870505, 1.        ]])

In [17]:
np.cov(a)

array([[0.91666667, 2.08333333],
       [2.08333333, 8.91666667]])

### import library

In [1]:
import numpy as np

#### np.array()

##### this method help us to create basic ndarray

In [2]:
l=[12,23,34,54,67,78]
l

[12, 23, 34, 54, 67, 78]

#### display type of an object

In [3]:
type(l)

list

#### convert list to numpy array

In [4]:
a1=np.array(l)
a1

array([12, 23, 34, 54, 67, 78])

In [5]:
type(a1)

numpy.ndarray

#### memory address of an array object

In [6]:
a1.data

#### datatype of an array object

In [7]:
a1.dtype

dtype('int32')

#### convert integer array to float

In [8]:
a1=a1.astype(float)
a1

array([12., 23., 34., 54., 67., 78.])

In [9]:
a1.dtype

dtype('float64')

#### generate equal spaced number between 0 to 20

In [10]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
np.arange(0,21,2) ### it will print difference of 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

#### generate number between 0 to 50 with space of 5

In [13]:
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
a2=np.arange(0,23)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

### shape of an array

##### shape of array

In [15]:
a2.shape

(23,)

##### size of array

In [16]:
a2.size

23

##### dimension

In [17]:
a2.ndim

1

##### byte consumed by one elemnt of an array object

In [18]:
a2.itemsize

4

#### bytes consumed by an array object

In [19]:
a2.nbytes

92

#### length of array

In [20]:
len(a2)

23

#### generate array of zeros

In [21]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### generate array of oncs

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### repeat 5 four time in an array

In [23]:
np.repeat(5,4)

array([5, 5, 5, 5])

##### repeat each elemnt in an array five times

In [24]:
a3=np.array([12,23,34]) ##each elemnt need to repaet 5 time
np.repeat(a3,5)

array([12, 12, 12, 12, 12, 23, 23, 23, 23, 23, 34, 34, 34, 34, 34])

#### array of 8's

In [25]:
np.full(5,8)

array([8, 8, 8, 8, 8])

In [2]:
import numpy as np

In [3]:
np.full(5,4) 

array([4, 4, 4, 4, 4])

#### generate aray of even numbers

In [4]:
a4=np.arange(1,100)
a4[a4%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

#### generate array of odd numbers

In [5]:
a4=np.arange(1,100)
a4[a4%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

### generate evently spaced 4 number between 10 to 25

In [6]:
np.linspace(10,25,5)

array([10.  , 13.75, 17.5 , 21.25, 25.  ])

In [7]:
np.linspace(10,25,10)

array([10.        , 11.66666667, 13.33333333, 15.        , 16.66666667,
       18.33333333, 20.        , 21.66666667, 23.33333333, 25.        ])

#### create array of random values

In [8]:
np.random.random(4)

array([0.26861552, 0.66537342, 0.68111907, 0.02463767])

#### generate an array of random integer number

In [9]:
np.random.randint(0,100,10)

array([84, 59, 35,  0, 31, 19, 55, 84, 20, 15])

In [10]:
a5=np.random.uniform(5,10,8) ### 5 and 10 is not included all number b/w this will get printed
a5

array([8.00821654, 6.30950397, 8.55504962, 6.7590862 , 5.70900847,
       9.80038399, 5.34852692, 9.58991036])

In [11]:
np.floor(a5) ###fractional part will not execute

array([8., 6., 8., 6., 5., 9., 5., 9.])

In [12]:
np.trunc(a5) ###franctional part will not execute same as floor

array([8., 6., 8., 6., 5., 9., 5., 9.])

#### check version of version of numpy

In [13]:
print(np.__version__)

1.21.5


### creating array from list

In [15]:
### creating array from list
import numpy as np
a=np.array([12,22,23,34,45])
print(a)
print(type(a))

[12 22 23 34 45]
<class 'numpy.ndarray'>


### creating array from tuple

In [16]:
### creating array from tuple
at=np.array((12,22,23,34,45))
print(at)
print(type(at))

[12 22 23 34 45]
<class 'numpy.ndarray'>


### dimension

#### 0-D array

In [ ]:
##0 d array or scalar array are the elemnt in an array each value in array is od

In [17]:
ae=np.array(67)
print(ae)

67


In [18]:
ae.ndim

0

### 1-D array

In [ ]:
### array more than one elemnt is called 1d array

In [19]:
a1=np.array([56,78,89])
print(a1)

[56 78 89]


In [20]:
a1.ndim

1

### 2 D ARRAY

In [ ]:
### USED TO REPRESENT METRICS

In [21]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
a=["1","2","3"]
b=[4,5,6]
c=[7,8,9]
a3=np.array([a,b,c]) ### converting number to string(num can convert to sting bu string cant be convert to number)
print(a3)

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]


#### 3D ARRAY

In [ ]:
### array that has 2d array as its elemnts is called 3d array

In [23]:
a3=np.array([[[1,2,3],[4,5,6]],[[11,12,13],[22,33,44]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [22 33 44]]]


### acess array elemnt

In [24]:
a1=np.array([11,34,56,78,89]) ###printing first elemt of an array
print(a1[0])

11


In [25]:
print(a1[3])

78


### get secnd and fourth elemnt from the array and add it

In [ ]:
a1=np.array([11,34,56,78,89])


In [27]:
print(a1[1])

34


In [28]:
print(a1[3])

78


In [34]:
add=a1[1]+a1[3]
print(add)

112


In [ ]:
### subtraction

In [33]:
sub=a1[1]-a1[3]
print(sub)

-44


In [ ]:
### multiplication

In [32]:
mul=a1[1]*a1[3]
print(mul)

2652


In [36]:
a2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [37]:
print(a2[0,1])

2


In [38]:
print(a2[1,1])

7


In [39]:
print(a2[1,3])

9


In [40]:
print(a2[1,-1])

10


In [41]:
print(a2[0,-3],a2[1,1])

3 7


### slicing

In [42]:
a1


array([11, 34, 56, 78, 89])

In [43]:
print(a1[3:])

[78 89]


In [44]:
print(a1[:3])

[11 34 56]


In [45]:
print(a1[-4:-1])

[34 56 78]


In [46]:
print(a1[-4:])

[34 56 78 89]


In [47]:
print(a1[::3]) ### no end value start value so takig first value and 

[11 78]


In [48]:
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [49]:
print(a2[0,0:3]) ## 0 is first row and slicing from there

[1 2 3]


In [50]:
print(a2[1,1:4])

[7 8 9]


In [51]:
print(a2[0:1,0:3])

[[1 2 3]]


### data types in numpy

In [ ]:
##i-interger
#b-boolean
##u-unsigned integer
##f-float
##c-complex float
## m-datetime
##o-object
##s-string
##u-unicode string


In [52]:
import numpy as np

In [53]:
ast=np.array(["deepika","karan","joy"])
print(ast.dtype)

<U7


In [54]:
a1=np.array([11,34,56,78,89])
a1

array([11, 34, 56, 78, 89])

In [55]:
print(a1.dtype)

int32


In [57]:
arr=np.array([1,256,31,4098],dtype="S")
print(arr)
print(arr.dtype) ## WHEN ADD DTYPE AUTOMATIALLY CONVERT TO THAT TYPE.HERE S FOR STRING AND CONVERTED TO STRING

[b'1' b'256' b'31' b'4098']
|S4


In [58]:
arr=np.array(['1','2','3','4'])
print(arr)
print(arr.dtype)

['1' '2' '3' '4']
<U1


In [59]:
ai=np.array([1,2,3,4],dtype="i4")
ai

array([1, 2, 3, 4])

In [60]:
print(ai.dtype)

int32


### operation on array

In [61]:
ar=np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### sum

In [62]:
ar.sum()

45

#### cumulative sum

In [63]:
cs=np.cumsum(ar) ###  eac value is sum of previous elmnt
print(cs)

[ 0  1  3  6 10 15 21 28 36 45]


In [64]:
print(np.cumsum(ar)) ### direct method find cumulative sum

[ 0  1  3  6 10 15 21 28 36 45]


### minimum value

In [65]:
ar.min()

0

#### maximum value

In [66]:
ar.max()

9

#### mean value

In [67]:
ar.mean()

4.5

#### median

In [68]:
np.median(ar)

4.5

In [69]:
ar=np.array([78,89,54,12,79,65])
ar

array([78, 89, 54, 12, 79, 65])

#### index value of minimum number in array

In [70]:
ar.argmin()

3

#### index value of maximum value in the array

In [71]:
ar.argmax()

1

### variance

In [72]:
np.var(ar)

640.4722222222222

#### standard deviation

In [73]:
np.std(ar)

25.307552671529148

### percentile

In [1]:
import numpy as np

In [2]:
ar=np.array([78,8,54,12,79,65])
ar

array([78,  8, 54, 12, 79, 65])

In [3]:
np.percentile(ar,75)

74.75

In [4]:
np.percentile(ar,50)

59.5

In [5]:
np.percentile(ar,25)

22.5

In [6]:
np.percentile(ar,0)

8.0

In [7]:
np.percentile(ar,100)

79.0

### copy of an array

#### changes in the old array not affected the copied array

In [8]:
ac=np.array([12,23,34,45,56])
y=ac.copy()
ac[3]=89
print(ac)
print(y)

[12 23 34 89 56]
[12 23 34 45 56]


### view

#### changes made in old aray olso reflect the copied array

In [9]:
ac=np.array([12,23,34,45,56])
y=ac.view()
ac[3]=89
print(ac)
print(y)

[12 23 34 89 56]
[12 23 34 89 56]


### diff b/w copy and view

###### copy is a new array and view is just a view of the original array.
##### the copy owns the data and any changes made to the copy will not affect original array and any mades to the original array will not affect the copy.
###### the view does not own the data and any changes made to the view will affect the original array and any changes made to the original array will affect the view.

## base

In [ ]:
##numpy array has the attribute base it return none if we use copy if use view it return the original one

In [11]:
ac=np.array([12,23,34,45,56])
y=ac.copy()
x=ac.view()
print(y.base)
print(x.base)

None
[12 23 34 45 56]


### reshaping

In [12]:
ar=np.array([1,2,34,45,56,67,78,89])
ar

array([ 1,  2, 34, 45, 56, 67, 78, 89])

In [13]:
n=ar.reshape(2,4) ## reshaping the aaray first value represnt row secnd is column
print(n)

[[ 1  2 34 45]
 [56 67 78 89]]


In [14]:
ar1=np.array([1,2,34,45,56,67,78])
ar1

array([ 1,  2, 34, 45, 56, 67, 78])

In [15]:
n=ar1.reshape(2,3)
print(n)

ValueError: cannot reshape array of size 7 into shape (2,3)

In [16]:
n=ar1.reshape(2,2)
print(n)

ValueError: cannot reshape array of size 7 into shape (2,2)

### iterating array

In [17]:
for i in ar:
    print(i)

1
2
34
45
56
67
78
89


In [18]:
for i in n:
    print(i)

[ 1  2 34 45]
[56 67 78 89]


In [19]:
for i in n:
    for j in i:
        print(j)

1
2
34
45
56
67
78
89


## join two array

In [20]:
a=np.array([1,2,3])
b=np.array([4,5,6])
con=np.concatenate((a,b))
print(con)

[1 2 3 4 5 6]


In [21]:
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[7,8,9],[10,11,12]])
print(c)
print(d)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [22]:
con1=np.concatenate((c,d),axis=0)
print(con1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [26]:
c=np.array([[1,2,3,6],[4,5,6,2]])
d=np.array([[7,8,9,8],[10,11,12,78]])

con1=np.concatenate((c,d),axis=1)
print(con1)


[[ 1  2  3  6  7  8  9  8]
 [ 4  5  6  2 10 11 12 78]]


### joining array using stack function

In [27]:
c=np.array([1,2,3])
d=np.array([7,8,12])
c

array([1, 2, 3])

In [28]:
d

array([ 7,  8, 12])

In [29]:
con1=np.stack((c,d),axis=1)
print(con1)

[[ 1  7]
 [ 2  8]
 [ 3 12]]


In [30]:
con1=np.stack((c,d),axis=0)
print(con1)

[[ 1  2  3]
 [ 7  8 12]]


## fstack()

In [31]:
c=np.array([1,2,3])
d=np.array([7,8,12])
con1=np.hstack((c,d))
print(con1)

[ 1  2  3  7  8 12]


### vstack()

In [32]:
c=np.array([1,2,3])
d=np.array([7,8,12])
con1=np.vstack((c,d))
print(con1)

[[ 1  2  3]
 [ 7  8 12]]


In [33]:
con1.ndim

2

## dstack()

In [34]:
c=np.array([1,2,3,96])
d=np.array([7,8,12,78])
con1=np.dstack((c,d))
print(con1)

[[[ 1  7]
  [ 2  8]
  [ 3 12]
  [96 78]]]


In [35]:
con1.dtype

dtype('int32')

In [36]:
con1.ndim

3

### splitting array

In [37]:
a1=np.array([31,21,30,44,15,61,70,18,9])
a1

array([31, 21, 30, 44, 15, 61, 70, 18,  9])

In [38]:
n=np.array_split(a1,4) ## number after array shows how much array need 
print(n)

[array([31, 21, 30]), array([44, 15]), array([61, 70]), array([18,  9])]


In [39]:
a1=np.array([31,21,30,44,15,61,70,18,9])
n=np.array_split(a1,5)
print(n)

[array([31, 21]), array([30, 44]), array([15, 61]), array([70, 18]), array([9])]


#### splitting 2D array

In [40]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [41]:
n1=np.array_split(a2,2)## splitting array in to 2
print(n1)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


In [42]:
print(n1[1]) ##represet secnd st array

[[ 7  8  9]
 [10 11 12]]


In [43]:
print(n1[0])

[[1 2 3]
 [4 5 6]]


### hsplit()

In [44]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
n1=np.hsplit(a2,3)
print(n1)

[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


In [46]:
n1[1]

array([[ 2],
       [ 5],
       [ 8],
       [11]])

In [47]:
n1[0]

array([[ 1],
       [ 4],
       [ 7],
       [10]])

### vsplit()

In [48]:
a2=np.array(([1,2,3],[4,5,6],[7,8,9],[10,11,12]))
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [49]:
n1=np.vsplit(a2,2)
print(n1)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]


### dsplit()

In [50]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [51]:
con1=np.dsplit(c,3)
print(con1)

[array([[[1],
        [4],
        [7]]]), array([[[2],
        [5],
        [8]]]), array([[[3],
        [6],
        [9]]])]


### searching array

In [53]:
arr=np.array([56,67,89,99,12,56,77])
a=np.where(arr==56) ## 56 in 2 time so 2 position will reflect
print(a)

(array([0, 5], dtype=int64),)


In [55]:
a=np.where(arr==1)## shows empty bz no such elemnt so empty
print(a)

(array([], dtype=int64),)


In [56]:
a=np.where(arr==12)
print(a)

(array([4], dtype=int64),)


### replace elemnts in array

In [57]:
ar=np.arange(1,21)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [58]:
rep=np.where(ar%2==0,0,ar) ## replce even number with zero
print(rep)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19  0]


### missing value in an array

In [59]:
a=np.array([1,np.nan,78,86,90,np.nan,8,np.nan])
a

array([ 1., nan, 78., 86., 90., nan,  8., nan])

In [60]:
np.isnan(a)

array([False,  True, False, False, False,  True, False,  True])

In [61]:
a

array([ 1., nan, 78., 86., 90., nan,  8., nan])

##### replace all missing value in an array with 65

In [62]:
a[np.isnan(a)]=65
a

array([ 1., 65., 78., 86., 90., 65.,  8., 65.])

#### check if array has any null values

In [63]:
np.isnan(a).any() ### check if array has any null values

False

### common items between 2 arrays

In [64]:
a=np.array([10,11,12,13,14,15,16,17])
b=np.array([12,13,45,67,34,10,11,78])

In [65]:
np.intersect1d(a,b)

array([10, 11, 12, 13])

### remove common elemnts

In [66]:
a

array([10, 11, 12, 13, 14, 15, 16, 17])

In [67]:
b

array([12, 13, 45, 67, 34, 10, 11, 78])

In [68]:
np.setdiff1d(a,b) ##elemnts in a not in b

array([14, 15, 16, 17])

In [69]:
np.setdiff1d(b,a)

array([34, 45, 67, 78])

### checking for elemnts in an array using isin()

In [70]:
a=np.array([10,20,30,40,50,60,78])
a

array([10, 20, 30, 40, 50, 60, 78])

In [71]:
np.isin(a,[40,60])

array([False, False, False,  True, False,  True, False])

### reverse an array

In [72]:
a=np.array([100,20,130,40,150,60,78])
a

array([100,  20, 130,  40, 150,  60,  78])

In [73]:
np.flip(a) ### flip is used to reverse an array

array([ 78,  60, 150,  40, 130,  20, 100])

### sort an array

In [74]:
b=np.array([67,43,23,11,89,65,45,88])
b

array([67, 43, 23, 11, 89, 65, 45, 88])

In [75]:
np.sort(b)

array([11, 23, 43, 45, 65, 67, 88, 89])

### operation on 2D array

In [76]:
a=np.array([[100,2,93],[41,5,6],[7,8,90]])
a

array([[100,   2,  93],
       [ 41,   5,   6],
       [  7,   8,  90]])

In [78]:
np.amin(a,axis=0) ##columnwise min value

array([7, 2, 6])

In [79]:
np.amin(a,axis=1) ##row wise min value

array([2, 5, 7])

In [80]:
np.amax(a,axis=0) ##column wise max value

array([100,   8,  93])

In [81]:
np.amax(a,axis=1) ##row wisw max value

array([100,  41,  90])